// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using it_bank.Api.Repository;

#nullable disable

namespace it_bank.Api.Repository.Migrations
{
    [DbContext(typeof(ItbankContext))]
    [Migration("20260702004123_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Proxies:ChangeTracking", false)
                .HasAnnotation("Proxies:CheckEquality", false)
                .HasAnnotation("Proxies:LazyLoading", true)
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("it_bank.Api.Model.Contas", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("IdUsuario")
                        .HasColumnType("bigint")
                        .HasColumnName("usuarioId");

                    b.Property<string>("NomeConta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomeConta");

                    b.Property<string>("TipoConta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipoConta");

                    b.Property<string>("Valor")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.HasIndex("IdUsuario");

                    b.ToTable("Contas", (string)null);
                });

            modelBuilder.Entity("it_bank.Api.Model.Deposito", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DataDeposito")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dataDeposito");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor");

                    b.Property<long>("idConta")
                        .HasColumnType("bigint")
                        .HasColumnName("nomeConta");

                    b.HasKey("Id");

                    b.HasIndex("idConta");

                    b.ToTable("Deposito", (string)null);
                });

            modelBuilder.Entity("it_bank.Api.Model.Tranferir", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("DataTransf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("dataTransf");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nomeConta");

                    b.Property<string>("Valor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("valor");

                    b.Property<long>("idConta")
                        .HasColumnType("bigint")
                        .HasColumnName("idConta");

                    b.HasKey("Id");

                    b.HasIndex("idConta");

                    b.ToTable("Tranferir", (string)null);
                });

            modelBuilder.Entity("it_bank.Api.Model.Usuarios", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nome");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.HasKey("Id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("it_bank.Api.Model.Contas", b =>
                {
                    b.HasOne("it_bank.Api.Model.Usuarios", "Usuario")
                        .WithMany("Contas")
                        .HasForeignKey("IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("it_bank.Api.Model.Deposito", b =>
                {
                    b.HasOne("it_bank.Api.Model.Contas", "Conta")
                        .WithMany("Depositos")
                        .HasForeignKey("idConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("it_bank.Api.Model.Tranferir", b =>
                {
                    b.HasOne("it_bank.Api.Model.Contas", "Conta")
                        .WithMany("Transferir")
                        .HasForeignKey("idConta")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Conta");
                });

            modelBuilder.Entity("it_bank.Api.Model.Contas", b =>
                {
                    b.Navigation("Depositos");

                    b.Navigation("Transferir");
                });

            modelBuilder.Entity("it_bank.Api.Model.Usuarios", b =>
                {
                    b.Navigation("Contas");
                });
#pragma warning restore 612, 618
        }
    }
}
