<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\it_bank.Api.Repository\it_bank.Api.Repository.csproj" />
    <ProjectReference Include="..\it_bank.Api.Services\it_bank.Api.Services.csproj" />
  </ItemGroup>

</Project>
